version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-test-app
    ports:
      - "8082:8082"
    volumes:
      - ./config:/app/config
    environment:
      - CONFIG_PATH=${CONFIG_PATH}
    depends_on:
      - db
    networks:
      - backend-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:14
    env_file:
      - .env
    container_name: postgres-db
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./tests/testdata/seed.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-net

networks:
  backend-net:

volumes:
  postgres-data:
